// lumina.config.ts
// Generated by npm run setup — edit freely.

import type { LuminaConfig } from "@/lib/config";

const config: LuminaConfig = {
  artist: {
    name: "Death Beach",
  },

  album: {
    title: "Beautiful Nothing",
  },

  theme: {
    accentColor: "#a78bfa",
    backgroundColor: "#080810",
    blurIntensity: "medium",
    fontDisplay: "inter",
  },

  tracks: [
    {
      id: "track-01",
      title: "Wayfaring Stranger",
      src: "/tracks/Wayfairing_Vocals.mp3",
      visual: {
        type: "reactive",
        scene: "translation",
      },
    },
    {
      id: "track-02",
      title: "Grateful",
      src: "/tracks/Grateful.mp3",
      visual: {
        type: "reactive",
        scene: "flower",
      },
    },
    {
      id: "track-03",
      title: "Trap(ped)",
      src: "/tracks/Trap(ped).mp3",
      visual: {
        type: "reactive",
        scene: "dimensional",
      },
    },
    {
      id: "track-04",
      title: "Drunk On The Mic by Mickey Shiloh (DOTM Remix)",
      src: "/tracks/DrunkOnTheMic_21.mp3",
      visual: {
        type: "reactive",
        scene: "mandala",
      },
      lyrics: {
        type: "timed",
        src: "/lyrics/track4.lrc",
      },
    }
  ],
  storeUrl: "https://www.deathbeachstudio.com/",

  features: {
    showPlaylist: true,
    autoplayNext: true,
  },
};

export default config;
